apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-logistics-back-end-deployment
  namespace: dev
  labels:
    app: master-logistics-back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-logistics-back-end
  template:
    metadata:
      labels:
        app: master-logistics-back-end
    spec:
      containers:
        - name: master-logistics-back-end
          image: IMAGE_NAME
          ports:
            - containerPort: 4090
          envFrom:
            - secretRef:
                name: master-logistics-back-end
