apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: dev
  labels:
    app: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: IMAGE_NAME
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: logging-service
