apiVersion: apps/v1
kind: Deployment
metadata:
  name: asg-statistics-backend-prod
  namespace: dev
  labels:
    app: asg-statistics-backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asg-statistics-backend-prod
  template:
    metadata:
      labels:
        app: asg-statistics-backend-prod
    spec:
      containers:
        - name: asg-statistics-backend-prod
          image: IMAGE_NAME
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: asg-statistics-backend-prod
