apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: absi-backend-prod
  namespace: dev
  annotations:
    nginx.org/client-max-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ingressClassName: nginx
  rules:
   - host: absi-apis.shelter-technology.com
     http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: absi-backend-prod
            port:
              number: 80
