apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecre
metadata:
  namespace: dev 
  name:  platform-radar-gateway-service
spec:
  backendType: secretsManager
  region: 
  data:
    - key: SECRET_NAME
      name: test
      property: test
    
