apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: prod
  name: asg-statistics-backend-prod
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: ASG-STATISTICS-BACKEND-PROD
      name: port
      property: port
    - key: ASG-STATISTICS-BACKEND-PROD
      name: db_host
      property: db_host
    - key: ASG-STATISTICS-BACKEND-PROD
      name: db_port
      property: db_port
    - key: ASG-STATISTICS-BACKEND-PROD
      name: db_username
      property: db_username
    - key: ASG-STATISTICS-BACKEND-PROD
      name: db_password
      property: db_password
    - key: ASG-STATISTICS-BACKEND-PROD
      name: db_name
      property: db_name
    - key: ASG-STATISTICS-BACKEND-PROD
      name: passwordEncryptionSecret
      property: passwordEncryptionSecret
    - key: ASG-STATISTICS-BACKEND-PROD
      name: jwtSecret
      property: jwtSecret
    
