apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecre
metadata:
  namespace: dev 
  name:  platform-radar-gateway-service
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: PORT
      property: PORT
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: basicDataIp
      property: basicDataIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: reviewIp
      property: reviewIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: radarGatewayIp
      property: radarGatewayIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: prosecutionIP
      property: prosecutionIP
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: notificationIp
      property: notificationIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: imagesIp
      property: imagesIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: loggingIp
      property: loggingIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: redisIp
      property: redisIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: gatewayRedisIp
      property: gatewayRedisIp
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: imagesPort
      property: imagesPort
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: licensingURL
      property: licensingURL
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: HTTPPORT
      property: HTTPPORT
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: normalViolationsConcurrency
      property: normalViolationsConcurrency
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: illegalStopConcurrency
      property: illegalStopConcurrency
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: pointToPointConcurrency
      property: pointToPointConcurrency
    - key: PLATFORM-RADAR-GATEWAY-SERVICE
      name: trafficFlowConcurrency
      property: trafficFlowConcurrency
