apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: dev
  name: platform-review-service
spec:
  backendType: secretsManager
  region: eu-west-2
  data:
    - key: PLATFORM-REVIEW-SERVICE
      name: PORT
      property: PORT
    - key: PLATFORM-REVIEW-SERVICE
      name: basicDataIp
      property: basicDataIp
    - key: PLATFORM-REVIEW-SERVICE
      name: reviewIp
      property: reviewIp
    - key: PLATFORM-REVIEW-SERVICE
      name: radarGatewayIp
      property: radarGatewayIp
    - key: PLATFORM-REVIEW-SERVICE
      name: prosecutionIP
      property: prosecutionIP
    - key: PLATFORM-REVIEW-SERVICE
      name: notificationIp
      property: notificationIp
    - key: PLATFORM-REVIEW-SERVICE
      name: imagesIp
      property: imagesIp
    - key: PLATFORM-REVIEW-SERVICE
      name: loggingIp
      property: loggingIp
    - key: PLATFORM-REVIEW-SERVICE
      name: redisIp
      property: redisIp
    
