apiVersion: v1
kind: Service
metadata:
  name: platform-notification-service
  namespace: dev
  labels:
    service: platform-notification-service
spec:
  type: NodePort
  selector:
    app: platform-notification-service
  ports:
  - port: 3005         # ClusterIP port
    targetPort: 3005   # Pod port




