apiVersion: v1
kind: Service
metadata:
  name: platform-radar-gateway-service
  namespace: dev
  labels:
    service: platform-radar-gateway-service
spec:
  type: ClusterIP
  selector:
    app: platform-radar-gateway-service
  ports:
  - port: 80         # ClusterIP port
    targetPort: 3003   # Pod port




