apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  namespace: NAMESPACE_NAME
  labels:
    service: APP_NAME
spec:
  type: NodePort
  selector:
    app: APP_NAME
  ports:
  - port: 80         # ClusterIP port
    targetPort: 80   # Pod port



    
