apiVersion: v1
kind: Service
metadata:
  name: platform-basic-data-service
  namespace: dev
  labels:
    service: platform-basic-data-service
spec:
  type: NodePort
  selector:
    app: platform-basic-data-service
  ports:
  - port: 3001         # ClusterIP port
    targetPort: 3001   # Pod port




